---
- name: "restart shinken"
  service: name=shinken state=restarted

- name: "restart shinken-arbiter"
  service: name="shinken-arbiter" state=restarted

- name: restart apache
  service: name=apache2 state=restarted

- name: "restart supervisor"
  service: name=supervisor state=restarted

- name: "restart gunicorn"
  service: name=gunicorn state=restarted

- name: "restart redis-server"
  service: name=redis-server state=restarted

- name: "restart thruk"
  service: name=thruk state=restarted
